// <auto-generated />
namespace CS_SKINS_ASP.Migrations.ApplicationDBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bleh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bleh));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011424239_bleh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
