//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_SKINS_ASP.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS_SKINS_ASP.Views.Home.ResourceHome", typeof(ResourceHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boites.
        /// </summary>
        public static string Boites {
            get {
                return ResourceManager.GetString("Boites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francois Brisson : joueur compétitif de CS : GO, il a participé dans plusieurs tournois. Rang : Global Elite.
        /// </summary>
        public static string ParCreateurF {
            get {
                return ResourceManager.GetString("ParCreateurF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcel Michel : expert de CS : GO, il a  participé a plusieurs tournois en tant qu&apos;organisateur et préposé a la logistique..
        /// </summary>
        public static string ParCreateurM {
            get {
                return ResourceManager.GetString("ParCreateurM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensemble, nous avons collaboré pour offrir une vue globale sur un point indispensable de CS : GO, les retexture, ou comme on dit, les skins!.
        /// </summary>
        public static string ParFinal {
            get {
                return ResourceManager.GetString("ParFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chez CS:SK, nous offrons la possibillité de visualiser toutes les skins de Counter Strike : Global Offensive, ainsi que leurs prix moyens sur
        ///        le marché en ce moment.
        /// </summary>
        public static string ParOpportunite {
            get {
                return ResourceManager.GetString("ParOpportunite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soutien.
        /// </summary>
        public static string Soutien {
            get {
                return ResourceManager.GetString("Soutien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous Joindre.
        /// </summary>
        public static string sTitreJoindre {
            get {
                return ResourceManager.GetString("sTitreJoindre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Propos.
        /// </summary>
        public static string Titreapropo {
            get {
                return ResourceManager.GetString("Titreapropo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous Contacter.
        /// </summary>
        public static string TitreContact {
            get {
                return ResourceManager.GetString("TitreContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les créateurs:.
        /// </summary>
        public static string TitreCreateur {
            get {
                return ResourceManager.GetString("TitreCreateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un site tellement utile.
        /// </summary>
        public static string TitreUtile {
            get {
                return ResourceManager.GetString("TitreUtile", resourceCulture);
            }
        }
    }
}
